### PR TITLE
Bug 549059 - RAT triggered after disposing the context under certain conditions

### PR DESCRIPTION
**Pull request by mmariia**

### CODE REVIEW

**Comment by hb91546** [comment]
Mariia, does this change fix Alex's simple test from his Bugzilla report?

**Review by mastanarao — APPROVED** [review]

**Comment by mmariia** [comment]
No, snippet from Bugzilla report won't be fixed. As RAT is removed if `change()` method returns false. In snippet `change()` method always returns true.

**Comment by hb91546** [comment]
I don't see any topics including removeRat at Eclipse 4 forum https://www.eclipse.org/forums/index.php/f/12/

Do you have any observations that you can put together for a new topic?

**Comment by mmariia** [comment]
Ok, I'll put something together and post a link here

**Comment by hb91546** [comment]
Would a similar change to the code in the eventType == ContextChangeEvent.DISPOSE block fix the Bugzilla snippet?

**Comment by mmariia** [comment]
You mean to use `event.getContext()` instead of `originatingContext`, like this:
```
if (eventType == ContextChangeEvent.DISPOSE) {
        ((EclipseContext) event.getContext()).removeRAT(this);
	return false;
}
```
It won't fix the snippet. Because `leaf` is reparented, but not disposed

**Comment by hb91546** [comment]
Alex's Bugzilla snippet is fixed with the following change to EclipseContext.removeChild
```
	public void removeChild(EclipseContext childContext) {
		synchronized (children) {
			for (Iterator<WeakReference<EclipseContext>> i = children.iterator(); i.hasNext();) {
				EclipseContext referredContext = i.next().get();
				if (referredContext == null) {
					i.remove();
					continue;
				}
				if (referredContext == childContext) {
					i.remove();
					break;
				}
			}
		}
		if (childContext == internalGet(this, ACTIVE_CHILD, true)) {
			set(ACTIVE_CHILD, null);
		}
	}
```

**Comment by ybova** [comment]
FYI, this PR is superseded by https://github.com/Halliburton-Landmark/eclipse.platform.runtime/pull/3

**Pull request closed without merging**
